.PHONY: build test race bench lab serve export
build:        ; go build -o bin/switchyard ./cmd/switchyard
test:         ; go test ./...
race:         ; go test -race -count=1 ./...
bench:        ; go test -run '^$$' -bench . -benchmem ./internal/...
lab: build    ; ./bin/switchyard lab run -scenario all -out results
serve: build  ; ./bin/switchyard lab serve -results results
export: build ; ./bin/switchyard lab export -results results -out docs
